# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.configuration-cache=false

minecraft_version=26.3
forge_version=66.0.2

archivesBaseName=NoChatRestrictions
modVersion=Forge-MC26.3-v1.3.0
manifestVersion=26.3-v1.3.0

net.minecraftforge.gradle.merge-source-sets=true