modLoader="javafml"
loaderVersion="[1,)"
license="WTFPL"
issueTrackerURL="https://github.com/Aizistral-Studios/No-Chat-Restrictions/issues"
iconFile="ncr_logo.png"

[[mods]]
modId="nochatrestrictions"
version="${mod_version}"
displayName="No Chat Restrictions"
displayURL="https://modrinth.com/project/no-chat-restrictions"
authors="Aizistral"
description="A mod dedicated to removing restrictions around the use of multiplayer features, including in-game chat."

[[dependencies.nochatrestrictions]]
    modId="neoforge"
    mandatory=true
    versionRange="[20.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nochatrestrictions]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.1,)"
    ordering="NONE"
    side="BOTH"
	
[[mixins]]
config="nochatrestrictions.mixins.json"
